autocmd FileType javascript call altr#define('test/*/%.test.js', 'spec/*/%.spec.js', 'spec/*/%_spec.js', 'src/%.js')
autocmd FileType ruby call altr#define('domain/*/%.rb', 'spec/*/%_spec.rb', 'test/*/_test.rb')
autocmd FileType ruby call altr#define('app/*/%.rb', 'spec/*/%_spec.rb', 'test/*/_test.rb')
autocmd FileType ruby call altr#define('lib/*/%.rb', 'spec/*/%_spec.rb', 'test/*/_test.rb')
nmap ,a <Plug>(altr-forward)
